//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: util_service.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf

///*
/// The requests and responses for different utility services.
///
/// Usage: instantiate `Proto_UtilServiceClient`, then call methods of this protocol to make API calls.
public protocol Proto_UtilServiceClientProtocol: GRPCClient {
    var serviceName: String { get }
    var interceptors: Proto_UtilServiceClientInterceptorFactoryProtocol? { get }

    func prng(
        _ request: Proto_Transaction,
        callOptions: CallOptions?
    ) -> UnaryCall<Proto_Transaction, Proto_TransactionResponse>
}

extension Proto_UtilServiceClientProtocol {
    public var serviceName: String {
        return "proto.UtilService"
    }

    ///*
    /// Generates a pseudorandom number.
    ///
    /// - Parameters:
    ///   - request: Request to send to prng.
    ///   - callOptions: Call options.
    /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
    public func prng(
        _ request: Proto_Transaction,
        callOptions: CallOptions? = nil
    ) -> UnaryCall<Proto_Transaction, Proto_TransactionResponse> {
        return self.makeUnaryCall(
            path: Proto_UtilServiceClientMetadata.Methods.prng.path,
            request: request,
            callOptions: callOptions ?? self.defaultCallOptions,
            interceptors: self.interceptors?.makeprngInterceptors() ?? []
        )
    }
}

#if compiler(>=5.6)
    @available(*, deprecated)
    extension Proto_UtilServiceClient: @unchecked Sendable {}
#endif  // compiler(>=5.6)

@available(*, deprecated, renamed: "Proto_UtilServiceNIOClient")
public final class Proto_UtilServiceClient: Proto_UtilServiceClientProtocol {
    private let lock = Lock()
    private var _defaultCallOptions: CallOptions
    private var _interceptors: Proto_UtilServiceClientInterceptorFactoryProtocol?
    public let channel: GRPCChannel
    public var defaultCallOptions: CallOptions {
        get { self.lock.withLock { return self._defaultCallOptions } }
        set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
    }
    public var interceptors: Proto_UtilServiceClientInterceptorFactoryProtocol? {
        get { self.lock.withLock { return self._interceptors } }
        set { self.lock.withLockVoid { self._interceptors = newValue } }
    }

    /// Creates a client for the proto.UtilService service.
    ///
    /// - Parameters:
    ///   - channel: `GRPCChannel` to the service host.
    ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
    ///   - interceptors: A factory providing interceptors for each RPC.
    public init(
        channel: GRPCChannel,
        defaultCallOptions: CallOptions = CallOptions(),
        interceptors: Proto_UtilServiceClientInterceptorFactoryProtocol? = nil
    ) {
        self.channel = channel
        self._defaultCallOptions = defaultCallOptions
        self._interceptors = interceptors
    }
}

public struct Proto_UtilServiceNIOClient: Proto_UtilServiceClientProtocol {
    public var channel: GRPCChannel
    public var defaultCallOptions: CallOptions
    public var interceptors: Proto_UtilServiceClientInterceptorFactoryProtocol?

    /// Creates a client for the proto.UtilService service.
    ///
    /// - Parameters:
    ///   - channel: `GRPCChannel` to the service host.
    ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
    ///   - interceptors: A factory providing interceptors for each RPC.
    public init(
        channel: GRPCChannel,
        defaultCallOptions: CallOptions = CallOptions(),
        interceptors: Proto_UtilServiceClientInterceptorFactoryProtocol? = nil
    ) {
        self.channel = channel
        self.defaultCallOptions = defaultCallOptions
        self.interceptors = interceptors
    }
}

#if compiler(>=5.6)
    ///*
    /// The requests and responses for different utility services.
    @available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
    public protocol Proto_UtilServiceAsyncClientProtocol: GRPCClient {
        static var serviceDescriptor: GRPCServiceDescriptor { get }
        var interceptors: Proto_UtilServiceClientInterceptorFactoryProtocol? { get }

        func makePrngCall(
            _ request: Proto_Transaction,
            callOptions: CallOptions?
        ) -> GRPCAsyncUnaryCall<Proto_Transaction, Proto_TransactionResponse>
    }

    @available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
    extension Proto_UtilServiceAsyncClientProtocol {
        public static var serviceDescriptor: GRPCServiceDescriptor {
            return Proto_UtilServiceClientMetadata.serviceDescriptor
        }

        public var interceptors: Proto_UtilServiceClientInterceptorFactoryProtocol? {
            return nil
        }

        public func makePrngCall(
            _ request: Proto_Transaction,
            callOptions: CallOptions? = nil
        ) -> GRPCAsyncUnaryCall<Proto_Transaction, Proto_TransactionResponse> {
            return self.makeAsyncUnaryCall(
                path: Proto_UtilServiceClientMetadata.Methods.prng.path,
                request: request,
                callOptions: callOptions ?? self.defaultCallOptions,
                interceptors: self.interceptors?.makeprngInterceptors() ?? []
            )
        }
    }

    @available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
    extension Proto_UtilServiceAsyncClientProtocol {
        public func prng(
            _ request: Proto_Transaction,
            callOptions: CallOptions? = nil
        ) async throws -> Proto_TransactionResponse {
            return try await self.performAsyncUnaryCall(
                path: Proto_UtilServiceClientMetadata.Methods.prng.path,
                request: request,
                callOptions: callOptions ?? self.defaultCallOptions,
                interceptors: self.interceptors?.makeprngInterceptors() ?? []
            )
        }
    }

    @available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
    public struct Proto_UtilServiceAsyncClient: Proto_UtilServiceAsyncClientProtocol {
        public var channel: GRPCChannel
        public var defaultCallOptions: CallOptions
        public var interceptors: Proto_UtilServiceClientInterceptorFactoryProtocol?

        public init(
            channel: GRPCChannel,
            defaultCallOptions: CallOptions = CallOptions(),
            interceptors: Proto_UtilServiceClientInterceptorFactoryProtocol? = nil
        ) {
            self.channel = channel
            self.defaultCallOptions = defaultCallOptions
            self.interceptors = interceptors
        }
    }

#endif  // compiler(>=5.6)

public protocol Proto_UtilServiceClientInterceptorFactoryProtocol: GRPCSendable {

    /// - Returns: Interceptors to use when invoking 'prng'.
    func makeprngInterceptors() -> [ClientInterceptor<Proto_Transaction, Proto_TransactionResponse>]
}

public enum Proto_UtilServiceClientMetadata {
    public static let serviceDescriptor = GRPCServiceDescriptor(
        name: "UtilService",
        fullName: "proto.UtilService",
        methods: [
            Proto_UtilServiceClientMetadata.Methods.prng
        ]
    )

    public enum Methods {
        public static let prng = GRPCMethodDescriptor(
            name: "prng",
            path: "/proto.UtilService/prng",
            type: GRPCCallType.unary
        )
    }
}
