included:
  - Examples/
  - Sources/Hedera/
  - Tests/

excluded:
  - .build/

disabled_rules:
  # TODO: re-enable once the project is deemed complete
  - todo
  # swift-format disagrees, swift-format has its own style lints.
  - opening_brace
  - trailing_comma
  # coverered by swift-format.
  - line_length

opt_in_rules:
  # deprecated & will be removed
  # - anyobject_protocol
  - anonymous_argument_in_multiline_closure
  - array_init
  - attributes
  - balanced_xctest_lifecycle
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  # - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_none_name
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_acl
  - explicit_top_level_acl
  # this conflicts with `explicit_acl` by making the ACL redundant
  # - extension_access_modifier
  - fallthrough
  - fatal_error_message

analyzer_rules:
  - capture_variable